package com.micro.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.micro.model.RoleResourcesPo;
import com.micro.model.RoleResourcesPoExample;

@Repository
public interface RoleResourcesPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resources
     *
     * @mbg.generated
     */
    long countByExample(RoleResourcesPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resources
     *
     * @mbg.generated
     */
    int deleteByExample(RoleResourcesPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resources
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(RoleResourcesPo key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resources
     *
     * @mbg.generated
     */
    int insert(RoleResourcesPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resources
     *
     * @mbg.generated
     */
    int insertSelective(RoleResourcesPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resources
     *
     * @mbg.generated
     */
    List<RoleResourcesPo> selectByExample(RoleResourcesPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resources
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RoleResourcesPo record, @Param("example") RoleResourcesPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resources
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RoleResourcesPo record, @Param("example") RoleResourcesPoExample example);
}