package com.micro.model;

import java.io.Serializable;

public class RoleResourcesPo  implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -517165554252750708L;

	/** 
    * 
    * DB Column Name: roleId
    */
    private Integer roleid;

    /** 
    * 
    * DB Column Name: resourcesId
    */
    private String resourcesid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resources.roleId
     *
     * @return the value of role_resources.roleId
     *
     * @mbg.generated
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resources.roleId
     *
     * @param roleid the value for role_resources.roleId
     *
     * @mbg.generated
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resources.resourcesId
     *
     * @return the value of role_resources.resourcesId
     *
     * @mbg.generated
     */
    public String getResourcesid() {
        return resourcesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resources.resourcesId
     *
     * @param resourcesid the value for role_resources.resourcesId
     *
     * @mbg.generated
     */
    public void setResourcesid(String resourcesid) {
        this.resourcesid = resourcesid;
    }
}