package com.micro.model;

import java.io.Serializable;

public class UserRolePo  implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 5498103170581013134L;

	/** 
    * 
    * DB Column Name: userId
    */
    private Integer userid;

    /** 
    * 
    * DB Column Name: roleId
    */
    private String roleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.userId
     *
     * @return the value of user_role.userId
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.userId
     *
     * @param userid the value for user_role.userId
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.roleId
     *
     * @return the value of user_role.roleId
     *
     * @mbg.generated
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.roleId
     *
     * @param roleid the value for user_role.roleId
     *
     * @mbg.generated
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid;
    }
}